version: '3.3'

services:
  postgres_Dogs:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin_Dogs:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=vic@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ROOT
    ports:
      - 5050:80
    volumes:
      - ./PGADMIN_DEFAULT:/var/lib/pgadmin